export const BINGO_NUMBERS = {
    // B
    1: { chant: 'Sa letrang B: Uno. B.. One. B : 1' },
    2: { chant: 'Sa letrang B: Kapamilya. Dos. B : 2' },
    3: { chant: '' },
    4: { chant: '' },
    5: { chant: '' },
    6: { chant: '' },
    7: { chant: '' },
    8: { chant: '' },
    9: { chant: '' },
    10: { chant: '' },
    11: { chant: '' },
    12: { chant: '' },
    13: { chant: '' },
    14: { chant: '' },
    15: { chant: '' },

    // I 
    16: { chant: '' },
    17: { chant: '' },
    18: { chant: '' },
    19: { chant: '' },
    20: { chant: '' },
    21: { chant: '' },
    22: { chant: '' },
    23: { chant: '' },
    24: { chant: '' },
    25: { chant: '' },
    26: { chant: '' },
    27: { chant: '' },
    28: { chant: '' },
    29: { chant: '' },
    30: { chant: '' },

    // N
    31: { chant: '' },
    32: { chant: '' },
    33: { chant: '' },
    34: { chant: '' },
    35: { chant: '' },
    36: { chant: '' },
    37: { chant: '' },
    38: { chant: '' },
    39: { chant: '' },
    40: { chant: '' },
    41: { chant: '' },
    42: { chant: '' },
    43: { chant: '' },
    44: { chant: '' },
    45: { chant: '' },

    // G
    46: { chant: '' },
    47: { chant: '' },
    48: { chant: '' },
    49: { chant: '' },
    50: { chant: '' },
    51: { chant: '' },
    52: { chant: '' },
    53: { chant: '' },
    54: { chant: '' },
    55: { chant: '' },
    56: { chant: '' },
    57: { chant: '' },
    58: { chant: '' },
    59: { chant: '' },
    60: { chant: '' },

    // O
    61: { chant: '' },
    62: { chant: '' },
    63: { chant: '' },
    64: { chant: '' },
    65: { chant: '' },
    66: { chant: '' },
    67: { chant: '' },
    68: { chant: '' },
    69: { chant: '' },
    70: { chant: '' },
    71: { chant: '' },
    72: { chant: '' },
    73: { chant: '' },
    74: { chant: '' },
    75: { chant: '' },
}